stages:
  - build

variables:
  IMAGE_NAME: $CI_REGISTRY/pengpeng/webdav-s3
  VERSION: v1.0.0

build:
  image: docker:23.0.6-dind
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$VERSION .
    - docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME:$VERSION
    - docker push $IMAGE_NAME:latest
  tags:
    - docker
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"